name: stopwatch
description: A stopwatch app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  async: ^2.13.0
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  core:
    path: packages/core
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  fake_async: ^1.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.2.1
  integration_test:
    sdk: flutter
  intl: ^0.20.2
  logging: ^1.3.0
  mocktail: ^1.0.4
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  utils:
    path: packages/utils

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
